[package]
name = "tap"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
env_logger = "0.9.0"
toml = "0.5.8"
home = "0.5.3"
log = "0.4.14"
colored = "2"
